### ISSUE TITLE
autosplits not working

### ISSUE THREAD

**Issue by Mista-Roy** [EnthusiastNT/haydee2#2]
had autosplits working a week ago for speedrunning haydee 2, now it doesnt work, maybe cause new update for livesplits? but deactivating and reactivating them in edit splits and redownloading livesplits and even trying it from the raw code text file doesnt work at all, any idea why autosplitting doesnt work anymore for haydee 2? the only time the timer activates auto is from starting the game from steam, never from resetting runs or even clicking start from new game.

**Comment by EnthusiastNT** [comment]
Yes, it's because of the update... Most auto-splitters need adjusting after every update. This takes a few hours, and I don't know when I have time.

You should let the Haydee developers know in the Steam forums, just so they are aware there is interest in using an AutoSplitter!

Note, you can install a previous version from Steam:
https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/

**Comment by Mista-Roy** [comment]
The developer of what? Livesplits? Or something else? Also thanks for replying, I really utilize the autosplits in my runs. Amazingly done.
-------- Original message --------From: Enthusiast ***@***.***> Date: 2021-12-09  11:14 a.m.  (GMT-06:00) To: EnthusiastNT/haydee2 ***@***.***> Cc: Mista-Roy ***@***.***>, Author ***@***.***> Subject: Re: [EnthusiastNT/haydee2] autosplits not working (Issue #2) 
Yes, it's because of the update... The autosplitter (any autosplitter actually) needs adjustment with every update. This takes a few hours, and I don't know if and when I have the time. You should let the developer know that this is a problem (which could easily be fixed from his side). It seems there are only like 2 people who ever used the autosplitter, though.

**Comment by EnthusiastNT** [comment]
Oh, I meant the Haydee developer. Maybe post in the Steam forum? Just so they are aware.

**Comment by EnthusiastNT** [comment]
Note, you can install a previous version from Steam:
https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/

**Comment by Mista-Roy** [comment]
Thank you for the idea, but I tried it and it still doesn't work, the splits auto start only when I start the game and not when in game, but im not sure which manifest to use, I only could find one by going to the database and finding the new update manifest then seeing there's been a manifest change and I used that ID, not sure how to find older ones.
-------- Original message --------From: Enthusiast ***@***.***> Date: 2021-12-19  6:33 a.m.  (GMT-06:00) To: EnthusiastNT/haydee2 ***@***.***> Cc: Mista-Roy ***@***.***>, Author ***@***.***> Subject: Re: [EnthusiastNT/haydee2] autosplits not working (Issue #2) 
Note, you can install a previous version from Steam:
https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/

**Comment by EnthusiastNT** [comment]
Should work now. Have fun!

**Comment by Mista-Roy** [comment]
It works, hopefully they'll stay working from now on, thank you for your
help, I'll be practicin runs all day.
